#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷‍♂️ 🏗️ 🧪 Styling, testing and building project before commit 👷‍♂️ 🏗️ 🧪'

# Check Prettier standards
npm run check-format ||
(
    echo '❌❌❌ Prettier Check Failed. Run npm run format, add changes and try commit again ❌❌❌';
    false;
)

# Check ESLint standards
npm run check-lint ||
(
        echo '❌❌❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again ❌❌❌'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌❌❌ Failed Type check. Make the changes required above ❌❌❌'
    false;
)

# If everything passes build and commit
echo '✅✅✅ Code looks good.. Trying to build now ✅✅✅'

npm run build ||
(
    echo '❌❌❌ Next build failed: View the errors above to see why ❌❌❌'
    false;
)

# Finished successfully
echo '🎉🎉🎉 Everything passed, committing now 🎉🎉🎉'
